apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: devops-tools
spec:
  template:
    spec:
      serviceAccountName: jenkins-admin-dev
      containers:
        - name: jenkins
          volumeMounts:
            - name: jenkins-data-dev
              mountPath: /var/jenkins_home_dev

      volumes:
        - name: jenkins-data-dev
          persistentVolumeClaim:
              claimName: jenkins-pv-claim
