apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: website
  namespace: wordpress
  labels:
    app: website-wp
  # annotations:
  #   cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - wordpress.hoanghd.com
    secretName: website-tls
  rules:
  - host: wordpress.hoanghd.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: website-wp
            port:
              number: 80







# openssl req -x509 -newkey rsa:4096 -keyout /home/wiki/key.pem -out  /home/wiki/cert.pem -days 365 -nodes -subj '/CN=wordpress.hoanghd.com'
# kubectl create secret generic website-tls --from-file=key.pem --from-file=cert.pem --namespace=wiki-hoanghd

# $  kubectl get secret -n wiki-hoanghd
# NAME                  TYPE                                  DATA   AGE
# default-token-cj7jv   kubernetes.io/service-account-token   3      14h
# mysql                 Opaque                                6      14h
# website-tls           Opaque                                2      12s