apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: website
  namespace: wiki-hoanghd
  labels:
    app: website-wp
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-ciphers: "TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256"
    nginx.ingress.kubernetes.io/ssl-certificate: "ssl-cert"
spec:
  rules:
  - host: wordpress.hoanghd.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: website-wp
            port:
              name: http

