
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wiki-hoanghd
resources:
- ../../base
- namespace.yaml
# - certificate.yaml
- clusterissuer.yaml

patches:
- path: mysql-deployment.yaml
- path: mysql-longhorn-patch.yaml
- path: wordpress-deployment.yaml
- path: wordpress-longhorn-patch.yaml
- path: ingress-patch.yaml