apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: website-mysql-pvc
  namespace: wordpress
  labels:
    app: matbao-website-mysql
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi