apiVersion: builtin
kind: Transform
metadata:
  name: replace-persistentvolume
patches:
- path: ../../base/jenkins/persistentvolume.yaml
  target:
    group: ""
    kind: PersistentVolume
    name: jenkins-pv-volume
    namespace: devops-tools
  transform: |-
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: jenkins-pv-volume
      labels:
        type: local
    spec:
      accessModes:
      - ReadWriteMany
      capacity:
        storage: 20Gi
      claimRef:
        apiVersion: v1
        name: jenkins-pv-claim
        namespace: devops-tools
      csi:
        driver: driver.longhorn.io
        fsType: ext4
        volumeAttributes:
          numberOfReplicas: "2"
        volumeHandle: jenkins-pv-volume
      storageClassName: local-storage
