apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devops-tools-slave
resources:
  - ../../../jenkins/base
  - namespace.yaml
  - clusterrole.yaml
  - serviceaccount.yaml
  - clusterroledinding.yaml

patches:
- path: longhorn-patch.yaml
- path: deployment-patch.yaml
- path: ingress-patch.yaml