# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: jenkins-pv-claim
#   namespace: devops-tools
# spec:
#   storageClassName: local-storage
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 3Gi

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
  namespace: devops-tools
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-storage
  volumeName: jenkins-pv-volume
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 20Gi